config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :invitations => 'users/invitations' }, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root 'home#index'
  resources :user, :groups
  

  post 'users/add_user_to_group' => 'user#add_user_to_group', as: :add_user
  get 'users/leave/:group_id' => 'user#leave_group', as: :leave_group

  get 'locations/search' => 'locations#search', as: :foursquare_query

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: :groups_users
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  attr_accessor :invited_group_id

  has_and_belongs_to_many :groups, join_table: :groups_users
  has_many :interests

  accepts_nested_attributes_for :interests, allow_destroy: true

  default_scope { includes(:groups, :interests) }

  def friendly_title
    self.name.present? ? self.name : self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user

  private

    def require_user
      unless current_user
        redirect_to root_path
      end
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save
    current_user.groups << @group
    redirect_to @group
  end

  def show
    @group = Group.find(params[:id])
    check_group_membership(@group)
  end

  def edit
    @group = Group.find(params[:id])
    check_group_membership(@group)
  end

  def update
    @group = Group.find(params[:id])
    check_group_membership(@group)

    @group.update_attributes(group_params)
    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :picture)
  end

  def check_group_membership(group)
    raise ActionController::RoutingError.new('Not Found') unless current_user.groups.include?(group)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ActionController::Base
  include Foursquare2

  def search
    q = params[:query]
    @results = search_venues(q)["venues"].to_json
    render layout: "application"
  end

  private

  def search_venues(q)
      client.search_venues(:ll => '37.792808, -122.402047', :query => q, :v => '20140204', :radius => 1000, :limit => 5)
  end

  def client
      @client ||= Foursquare2::Client.new(:client_id => ENV["FS_APP_ID"], :client_secret => ENV["FS_APP_SECRET"])
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    check_for_association(@user) if current_user.id != @user.id
  end

  def edit
    @user = User.find(params[:id])
    @grouped_options = interest_categories
    check_identity(@user)
  end

  def update
    @user = User.find(params[:id])
    @user.interests.delete_all
    if current_user.id != @user.id
      flash[:notice] = "tsk, tsk, tsk"
    else
      @user.update_attributes(user_params)
    end

    redirect_to user_path(current_user)
  end

  def add_user_to_group
    user_to_invite = params[:user_email]
    group_to_add = Group.find(params[:group_id])

    existing_user = User.find_by email: user_to_invite

    if existing_user
      action = "added"
      existing_user.groups << group_to_add unless existing_user.groups.include?(group_to_add)
    else
      action = "invited"
      User.invite!(email: user_to_invite, invited_group_id: group_to_add.id)
    end

    flash[:notice] = "The user was #{action} successfully."
    redirect_to group_path(group_to_add)
  end

  def leave_group
    group_to_leave = params[:group_id]
    current_user.groups.delete(group_to_leave)
    flash[:notice] = "successfully left group"
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, interests_attributes: [:interest_type, :details, :sentiment, :user_id])
  end

  def check_identity(user)
    raise ActionController::RoutingError.new('Not Found') if user.id != current_user.id
  end

  def check_for_association(user)
    possible_associations = []
    user.groups.each do |group|
      possible_associations << group.users.pluck('id')
    end

    raise ActionController::RoutingError.new('Not Found') unless possible_associations.flatten!.include?(current_user.id)
  end

  def interest_categories
    {
      "Food" => [
        ["Indian", "indian"],
        ["Chinese", "chinese"],
        ["Japanese", "japanese"],
        ["Mexican", "mexican"],
        ["Italian", "italian"],
        ["Pub", "pub"]
      ],
      "Drink" => [
        ["Coffee", "coffee"],
        ["Smoothie", "smoothie"],
        ["After work beer", "beer"],
        ["After work cocktail", "cocktail"],
        ["Bubble tea", "bubble tea"]
      ],
      "Hobby" => [
        ["Surfing", "surfing"],
        ["Basketball", "bball"],
        ["Running", "running"],
        ["Opera", "opera"],
        ["Biking", "biking"],
        ["Homebrewing", "homebrew"],
        ["Rock climbing", "climbing"],
        ["Hiking", "hiking"]
      ]
    }
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  def edit
    resource.invitation_token = params[:invitation_token]
    @group_to_add = params[:group_id]
    render :edit
  end

    # PUT /resource/invitation
  def update
    self.resource = accept_resource
    resource.groups << Group.find(params[:group_to_add])
    if resource.errors.empty?
      yield resource if block_given?
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message :notice, flash_message if is_flashing_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_accept_path_for(resource)
    else
      respond_with_navigational(resource){ render :edit }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/views/application/_footer.html.haml
%footer
  %p &copy; 2014 All You Can Meet&trade; 

app/views/application/_header.html.haml
%header
  = render 'application/navigation'
  - flash.each do |name, msg|
    = content_tag :div, msg, class: name

app/views/application/_navigation.html.haml
%nav.main_nav.navbar.navbar-default.navbar-fixed-top{ :role => "navigation" }
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ :data => { :toggle => "collapse", :target => "#main_nav" } }
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "All You Can Meet", root_path, :class => "navbar-brand"

    #main_nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - unless user_signed_in?
          %li= link_to "Log In", new_user_session_path
          %li= link_to "Register", new_user_registration_path
        - if user_signed_in?
          %li= link_to "New Group", new_group_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right.user_nav
          %li.dropdown
            %a.dropdown-toggle{ :href => "#", :data => { :toggle => "dropdown" } }
              My Groups
              %span.caret
            %ul.group-list.dropdown-menu
              - current_user.groups.each do |group|
                %li
                  = link_to group.name, group_path(group)
          %li= link_to current_user.friendly_title, user_path(current_user)
          %li= link_to "Log out", destroy_user_session_path, :method => :delete

app/views/groups/edit.html.haml
.main
  %h1 Edit group

  = form_for @group, :action => :update do |f|
    .block
      = f.label :name, "Name"
      = f.text_field :name
    .block
      = f.label :description, "Description"
      = f.text_field :description
    .block
      = f.label :picture, "Picture"
      = f.text_field :picture

    %menu.submit
      = f.button :Submit

app/views/groups/new.html.haml
.main
  %h1 Create a new group

  = form_for @group, :action => :create do |f|
    .block
      = f.label :name, "Name"
      = f.text_field :name
    .block
      = f.label :description, "Description"
      = f.text_field :description
    .block
      = f.label :picture, "Picture"
      = f.text_field :picture

    %menu.submit
      = f.button :Submit

app/views/groups/show.html.haml
.main
  %h1= @group.name
  %p= @group.description
  %h2 Users
  %ul
  - @group.users.each do |user|
    %li
      = link_to user.name? ? user.name : user.email, user_path(user)

  %h2 Suggested places

  %h2 Invite users to this group
  = form_tag( controller: "user", action: "add_user_to_group" ) do
    = label_tag(:user_email, "Email to invite")
    = text_field_tag(:user_email)
    = hidden_field_tag(:group_id, @group.id)
    = submit_tag("Invite")

  = link_to "Edit this group", edit_group_path(@group)

app/views/home/index.html.haml
.row
  .col-md-8
    %h1= "hello #{user_signed_in? ? current_user.email : 'world'}"

    = form_tag({ controller: "locations", action: "search"}, method: "get") do
      = text_field_tag(:query, "", :class => "form-control", :style => "width: 33%; display: inline; height: 43px;")
      = submit_tag("Search", :class => "btn-primary", :style => "display: inline;")

    %button.btn-primary.create-event create new event

  .col-md-4
    - if user_signed_in?
      %h4 My Groups
      %ul
        - current_user.groups.each do |group|
          %li= link_to group.name, group_path(group)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
  %title All You Can Meet
  = stylesheet_link_tag    'application', media: 'all'
  = stylesheet_link_tag 'https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.css'
  = javascript_include_tag 'https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.js'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  .container
    = render 'application/header'
    .content
    = yield
    = render 'application/footer'

app/views/locations/search.html.haml
-# = form_tag( controller: "locations", action: "search" ) do
-#   = input_tag(:query)
-#   = submit_tag("Search")

.map-hero.col-md-6
  #map
.suggestions.col-md-6
  .list-group
    - JSON.parse(@results).each do |venue|
      .list-group-item
        .name= venue['name']
        .phone= venue['contact']['formattedPhone']
        .address= venue['location']['formattedAddress'][0]
        .city= venue['location']['formattedAddress'][1]

:javascript
  var venues = $.parseJSON("#{j @results}")

app/views/user/_interest_fields.html.haml
%fieldset.interests-fieldset
  = f.label(:interest_type, "Type")
  = f.select(:interest_type, options_for_select([ ["Food", "food"], ["Drink", "drink"], ["Hobby", "hobby"] ], :selected => f.object.interest_type), :class => 'type_select' )
  = f.label(:details, "Details")
  = f.select(:details, grouped_options_for_select(@grouped_options, :selected => f.object.details), :class => 'details_select' )
  = f.label :sentiment, "Sentiment"
  -# = f.select(:sentiment, options_for_select([ ["Yes","yes"], ["No", "no"], ["Maybe", "maybe"] ], :selected => f.object.sentiment), :class => 'sentiment_select')
  = f.text_field :sentiment
  = f.hidden_field :_destroy
  = f.label :_destroy, "Remove Interest", class: "remove_fields"

app/views/user/edit.html.haml
.main
  %h1 Edit your profile

  = form_for @user, :action => :update do |f|
    .block
      = f.label :name, "Name"
      = f.text_field :name
    .block
      = f.label :email, "Email"
      = f.text_field :email

    = f.fields_for :interests do |builder|
      = render 'interest_fields', f: builder

    = link_to_add_fields "Add Interest", f, :interests
    %menu.submit
      = f.button :Submit, :class => 'btn-primary'

app/views/user/show.html.haml
.main
  %h1= @user.name || "Hi"
  %h2= @user.email
  %h3 My Groups
  %ul
    - @user.groups.each do |group|
      %li
        = link_to group.name, group_path(group)
        - if current_user == @user
          = link_to "(leave)", leave_group_path(group)
  %h3 My Interests
  %ul.interests
    - @user.interests.each do |interest|
      %li
        %p.interest-type= interest.interest_type + ':'
        %p= interest.details
        %p= interest.sentiment
  - if current_user == @user
    %p= link_to "Edit", edit_user_path(current_user)